# Generated by Django 5.0.6 on 2026-07-31 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(blank=True, max_length=255)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('resume_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('VERIFYING', 'Verifying'), ('INTERVIEWING', 'Interviewing'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=20)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('technical_accuracy', models.TextField(blank=True)),
                ('feedback_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(blank=True, max_length=50)),
                ('answer_text', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviewer.candidatesession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
    ]
